GET http://localhost:4567/med HTTP/1.1

###
GET http://localhost:4567/med/28 HTTP/1.1

###
POST http://localhost:4567/med HTTP/1.1

# Content-Type: "application/json"
{
    "id": 0,
    "name": "Dexa",
    "description": "obat panas",
    "base_price": 4000,
    "price": 5000,
    "stock": 0
}

###
PUT http://localhost:4567/med/29 HTTP/1.1

# Content-Type: "application/json"
{
    "id": 29,
    "name": "Dexa 10%",
    "description": "obat panas",
    "base_price": 4000,
    "price": 5000,
    "stock": 0
}

###

DELETE http://localhost:4567/med/29 HTTP/1.1

###
POST http://localhost:4567/purchase/save HTTP/1.1
# Content-Type: "application/json"

{
    "date": "2021-08-08",
    "supplier_id": 1,
    "total": 10000,
    "purchase_code": "123",
    "med_id": 28,
    "qty": 10,
    "purchase_id": 1
}
