GET http://localhost:4567/med?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.ewogICJ1c2VybmFtZSI6ICJhZG1pbiIsCiAgInRpbWVzdGFtcCI6IDE2Mzg2NzI2NzkyNzQKfQ.dLKyg4WLonYNKfPfHOsdrTlbP14J8tu34Y17lbRwI9k HTTP/1.1

###
GET http://localhost:4567/med/44?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.ewogICJ1c2VybmFtZSI6ICJhZG1pbiIsCiAgInRpbWVzdGFtcCI6IDE2Mzg1ODU4ODk0NDYKfQ.pZi6OeIWp8tPvcAg-GpsnFaYS2xwwci93lQqTv9ndCg HTTP/1.1

###
POST http://localhost:4567/med?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.ewogICJ1c2VybmFtZSI6ICJhZG1pbiIsCiAgInRpbWVzdGFtcCI6IDE2Mzg2NzI2NzkyNzQKfQ.dLKyg4WLonYNKfPfHOsdrTlbP14J8tu34Y17lbRwI9k HTTP/1.1

# Content-Type: "application/json"
{
    "id": 0,
    "name": "Obat baru pisan nnnnnn",
    "description": "obat panas baru baru",
    "basePrice": 4000,
    "price": 5000,
    "stock": 0
}

###
PUT http://localhost:4567/med/29 HTTP/1.1

# Content-Type: "application/json"
{
    "id": 29,
    "name": "Dexa 10%",
    "description": "obat panas",
    "base_price": 4000,
    "price": 5000,
    "stock": 0
}

###

DELETE http://localhost:4567/med/29 HTTP/1.1

###
POST http://localhost:4567/purchase/save HTTP/1.1
# Content-Type: "application/json"

{
    "date": "2021-08-08",
    "supplier_id": 1,
    "total": 10000,
    "purchase_code": "123",
    "med_id": 28,
    "qty": 10,
    "purchase_id": 1
}

###
POST http://localhost:4567/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

